#define _void 							1	//"Code for void"
#define _INT 							2	//"Code for int"
#define _FLOAT 							3	//"Code for float"
#define _WHILE 							4	//"Code for WHILE"
#define _IF								5	//"Code for IF"
#define LEFT_PAREN 						6	//"Code for ("
#define RIGHT_PAREN 					7	//"Code for )"
#define LEFT_CURLY_BRACKET 				8	//"Code for {"
#define RIGHT_CURLY_BRACKET 			9	//"Code for }"
#define IDENTIFIER						10
#define INT_VAL 						11
#define FLOAT_VAL						12
#define EQUAL							13	//"Code for ="
#define CMP_EQUAL						14	//"Code for =="
#define CMP_GT							14	//"Code for >"
#define CMP_GT_EQUAL					15	//"Code for >="
#define CMP_LT							16	//"Code for <"
#define CMP_LT_EQUAL					17	//"Code for <="
#define MINUS							18	//"Code for -"
#define PLUS							19	//"Code for +"
#define MULTIPLY						20	//"Code for *"
#define DIVIDE							21	//"Code for /"
#define COMMA							22	//"Code for ,"
#define SEMI_COLON						23	//"Code for ;"
#define COMMENT							24	//"Code for //"
